"""añadiendo columnas de origen y destino de la ciudad

Revision ID: 34518d30ffce
Revises: 567ced427324
Create Date: 2026-03-12 13:28:12.333802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34518d30ffce'
down_revision: Union[str, Sequence[str], None] = '567ced427324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('origin_country', sa.String(), nullable=True))
    op.add_column('flights', sa.Column('destination_country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'destination_country')
    op.drop_column('flights', 'origin_country')
    # ### end Alembic commands ###
