"""Add services and booking_services tables

Revision ID: d7fddb4dd320
Revises: 45c7af0d2d1d
Create Date: 2026-03-21 18:26:26.127699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fddb4dd320'
down_revision: Union[str, Sequence[str], None] = '45c7af0d2d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_subscription', sa.Boolean(), nullable=True),
    sa.Column('location_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_table('booking_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_services_id'), 'booking_services', ['id'], unique=False)
    op.add_column('tours', sa.Column('duration_hours', sa.Integer(), nullable=True))
    op.add_column('tours', sa.Column('difficulty_level', sa.String(), nullable=True))
    op.drop_column('tours', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tours', sa.Column('category', sa.VARCHAR(), nullable=True))
    op.drop_column('tours', 'difficulty_level')
    op.drop_column('tours', 'duration_hours')
    op.drop_index(op.f('ix_booking_services_id'), table_name='booking_services')
    op.drop_table('booking_services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
